#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom -b &
feh --bg-scale Pictures/wallhaven-7pmv93.jpg &
pgrep -x xfce-polkit > /dev/null || /./usr/libexec/xfce-polkit &
xset -b &
flameshot &
pgrep -x polybar > /dev/null || polybar example &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.55
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Sxiv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr &
bspc config focused_border_color "#abbcda"
bspc config focus_follows_pointer true
