#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
./.local/bin/polybar example &
picom -b &
feh --bg-scale /home/marin/Pictures/wallhaven-m3vyx9.png &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.55
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr &
bspc config focused_border_color "#993399"
bspc config focus_follows_pointer true
